### ISSUE TITLE
multy motors and joints

### ISSUE THREAD

**Issue by geppetto32** [NaokiTakahashi12/cybergear_ros2#15]
Hello Naoki as i told before your code is the most advanced among others. 
My thing ... i tried to modify the cybergear_socketcan_driver_node.cpp to accept more motors but nothing seems to work ... so i reset everything and i am here now to ask if there is any simpler way to send msgs at diferent motors. I also tried to modify the node.parameters.md  like this part of code below  and send msg to each one seperatly but nothing happend. 
Thank you indeed. 

cybergear_socketcan_driver_node:
  ros__parameters:
    anguler_effort:
      max: 12.0
      min: -12.0
    anguler_position:
      max: 12.56637061
      min: -12.56637061
    anguler_velocity:
      max: 30.0
      min: -30.0
    command_topic_type: trajectory

    # Motor 1 
    motor_1:
      device_id: 127.0
      joint_name: cybergear_1
      pid_gain:
        kd: 0.0475
        kp: 0.3

    # Motor 2 
    motor_2:
      device_id: 126.0
      joint_name: cybergear_2
      pid_gain:
        kd: 0.05
        kp: 0.35

    primary_id: 0.0
    send_frequency: 16.0
    temperature:
      scale: 0.1
    torque_constant: 0.87
    update_param_frequency: 1.0
    ...............................................................................................................................................................
    saifer@saifer:~/ros2_ws$ ros2 topic pub /joint_trajectory trajectory_msgs/msg/JointTrajectory "{
  header: {
    stamp: {sec: 0, nanosec: 0},
    frame_id: ''
  },
  joint_names: ['cybergear_2'],
  points: [
    {
      positions: [10.0],  # Move to 0.5 radian (~28.6 degrees)
      time_from_start: {sec: 0.3, nanosec: 0}  # Move to the position in 1 second
    }
  ]
}"
......................................................................................................................................................................
saifer@saifer:~/ros2_ws$ ros2 topic pub /joint_trajectory trajectory_msgs/msg/JointTrajectory "{
  header: {
    stamp: {sec: 0, nanosec: 0},
    frame_id: ''
  },
  joint_names: ['cybergear_1'],
  points: [
    {
      positions: [10.0],  # Move to 0.5 radian (~28.6 degrees)
      time_from_start: {sec: 0.3, nanosec: 0}  # Move to the position in 1 second
    }
  ]
}"

**Comment by NaokiTakahashi12** [comment]
Hi geppetto32

Thank you for bringing up this issue. 
When I initially developed the software, I only had access to one CyberGear, so I couldn't test it with multiple motors. 
Now that I have access to multiple CyberGears, I will work on testing and provide a solution for running multiple motors simultaneously.

Once we find a solution to the problem, we will share it here.

**Comment by geppetto32** [comment]
![17256123446248062167513781656367](https://github.com/user-attachments/assets/04974eea-10d0-422d-bf08-4160590ea790)
Thats Great Naoki , we are waiting for you :) .

**Comment by NaokiTakahashi12** [comment]
We have confirmed that it is possible to control multiple CyberGear servo motors.
Below is the procedure for doing so:

## Step 1
Start a node for each motor you want to control.

terminal 1
```bash
ros2 run cybergear_socketcan_driver cybergear_position_driver_node --ros-args -p device_id:=127 -p joint_name:=cybergear_1 -r __node:=cybergear_1
```

terminal 2
```bash
ros2 run cybergear_socketcan_driver cybergear_position_driver_node --ros-args -p device_id:=126 -p joint_name:=cybergear_2 -r __node:=cybergear_2
```

## Step 2
Enable torque on the CyberGear servo motors.

```bash
ros2 service call /cybergear_1/enable_torque std_srvs/srv/SetBool "data: true"
ros2 service call /cybergear_2/enable_torque std_srvs/srv/SetBool "data: true"
```

## Step 3
Send control commands to each CyberGear.

```bash
ros2 topic pub /joint_trajectory trajectory_msgs/msg/JointTrajectory "{header: {stamp: now}, joint_names: [cybergear_1, cybergear_2], points: [{positions: [0.0, 0.0], time_from_start: {sec: 2}}, {positions: [0.5, -0.5], time_from_start: {sec: 4}}]}" --once
```

Please verify whether the CyberGear servo motors rotate correctly using the above procedure.

**Comment by geppetto32** [comment]
Thank you Naoki very much, i will test them later at evening. I have a consideration : if we attach a node to each cybergear we want to use ... isnt that going to use much more cpu usage? instead of using one node that controls every motor in an array-list of motors? 
Another valuble option would be by converting your work or adding a hardware interface for ros2 control....
e.g I am not that expert on programming and also i dont know if is ok writting here... if not ,i am sorry.

**Comment by NaokiTakahashi12** [comment]
Thank you for raising this issue.

As you mentioned, starting multiple nodes will increase CPU usage. For instance, on a Raspberry Pi 5 running at 100 Hz, the CPU usage per node averages around 1.3%. The primary overhead comes from the topic transfer between nodes.

If this CPU usage is a concern, it can be mitigated by using the `rclcpp_components` format, which we support.

Given these considerations, we chose to design the system with one node per motor to enable distributed processing. Specifically, we wanted to split the setup across two computers—one handling CAN as a ROS 2 topic, and the other focused on joint trajectory planning.

If `ros2_control`'s `hardware_interface` is supported, more responsive control can be achieved. However, optimal performance would require an RT-kernel, and the choice of OS may introduce contractual limitations. We do plan to support `ros2_control` in the future, though we don't have a confirmed timeline at this point.

**Comment by NaokiTakahashi12** [comment]
Reopen this issue again if necessary.

**Comment by DSJuanGuzman** [comment]
Hi Naoki, I've been working with CyberG

> ![17256123446248062167513781656367](https://private-user-images.githubusercontent.com/95494535/365098473-04974eea-10d0-422d-bf08-4160590ea790.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDkwNjEsIm5iZiI6MTcyNjc0ODc2MSwicGF0aCI6Ii85NTQ5NDUzNS8zNjUwOTg0NzMtMDQ5NzRlZWEtMTBkMC00MjJkLWJmMDgtNDE2MDU5MGVhNzkwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEyMjYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDE3MGQ3OWVmNDUzMDg4NmU3M2FlZTM2MzJjYzRjY2Y2Zjg1OWUwOWM0YTU3OTAyNzhlNTU3ZGIyMGM2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luCy8YdMzD8eZuOLpy5agGb88vly6giEzX1vM5hIvu8) Thats Great Naoki , we are waiting for you :) .

Hi Naoki!, Im working with cybergear motors right now, But im experimenting a strange problem with the zero position, When disconnected from the mains the motor loses this position, is there any way to keep a stable 0 always in the same place, I would be very grateful if you can help me and I can not find much information about this motor on the internet.

**Comment by NaokiTakahashi12** [comment]
Hi Juan,

I believe that the cause of this phenomenon in CyberGear motors cannot be resolved through software. Most likely, the encoder used in the CyberGear motor is a magnetic rotary encoder, which loses angle information when the power is interrupted. To address this, the CyberGear motor has a feature to reset the angle to zero, which can be used to avoid the issue, although it may be inconvenient.
